config/routes.rb
Rails.application.routes.draw do
	devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "calculations#get_values"
  post '/get_sizes'  => "calculations#get_sizes"
  post '/find_odd_values'  => "calculations#find_odd_values"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  #filter
  before_action :authenticate_user!
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController

	def get_values
		@calculation = User.new
	end

	def get_sizes
		@count = 0
		@list = []
		@a = params[:q].chomp.to_i
	end

	def find_odd_values
		@array = params[:q].collect { |g| g.to_i }
		@var = @array.uniq
		puts "number of steps to find odd element is 1"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/calculations/find_odd_values.html.erb
<p>The values of Array is </p> 
<%= @var.each_with_index.sort %>
<p>The highest odd value is </p>
<%= @var.max %>
<p>The smallest odd value is </p>
<%= @var.min %>
<br>
<p>number of steps to find odd element is 1 </p>

app/views/calculations/get_sizes.html.erb
<p>Enter the weight of each one</p>

<%= form_tag(find_odd_values_path, :method => "post") do %>
 <% @a.times do |g| %>
   <% @count += 1 %>
   <%= label_tag(:q, "#{@count} Number:") %>
   <%= text_field_tag "q[]" %>
   <br>
 <% end %>
<%= submit_tag("submit") %>
<% end %>

app/views/calculations/get_values.html.erb
<p>Enter number of elements </p>
<%= form_tag(get_sizes_path, :method => "post") do %>
  <%= label_tag(:q, "Number:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("submit") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>InterviewTest</title>
	<%= csrf_meta_tags %>

	<%#= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<% if user_signed_in? %>
	<li>
		<%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
	</li>
	<% else %>
	<li>
		<%= link_to('Login', new_user_session_path)  %>  
	</li>
	<% end %>
	<%= yield %>
</body>
</html>